### ISSUE TITLE
Other knn failed

### ISSUE THREAD

**Issue by kimdn** [idsia-robotics/RandLA-Net-pytorch#5]
Thank you for sharing this wonderful code.

I was able to run with 
'k_n': 16,  # KNN

However, when I tried to use k_n=8
it showed

`Train:   0%|          | 0/500 [00:02<?, ?it/s]
epoch:   0%|          | 0/300 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/train.py", line 15, in <module>
    train_randlanet_model(train_set_list =["data/pc_id=13/", "data/pc_id=14/", "data/pc_id=16/"],
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/training.py", line 395, in train_randlanet_model
    train_model(model, hyperpars['max_epoch'], hyperpars['max_patience'], train_loader, test_loader, device,
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/training.py", line 91, in train_model
    train_loss, train_acc = train_epoch(device, loss, model,
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/training.py", line 194, in train_epoch
    outputs = model(inputs)
  File "/home/kimd999/bin/Miniconda3-py39_4.10.3-Linux-x86_64/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/model.py", line 48, in forward
    x = encoder(x, inputs['xyz'][i], inputs['neigh_idx'][i])
  File "/home/kimd999/bin/Miniconda3-py39_4.10.3-Linux-x86_64/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/model.py", line 95, in forward
    f_pc = self.bb(xyz, f_pc, neigh_idx)
  File "/home/kimd999/bin/Miniconda3-py39_4.10.3-Linux-x86_64/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/model.py", line 113, in forward
    f_xyz = relative_pos_encoding(xyz, neigh_idx)
  File "/home/kimd999/script/python/apt/randla-net-pytorch_idsia_pnnl/model/model.py", line 156, in relative_pos_encoding
    relative_xyz = repeated_xyz - neighbor_xyz
RuntimeError: The size of tensor a (16) must match the size of tensor b (8) at non-singleton dimension 3`

Changing
`'d_out': [16, 64, 128, 256, 512], # feature dimension`
to
`'d_out': [8, 64, 128, 256, 512],`
didn't help as well.

**Comment by Gabry993** [comment]
Hi kimdn,
unfortunately, I won't be able to test the code shortly, but I think this is the issue:
https://github.com/idsia-robotics/RandLA-Net-pytorch/blob/main/model/model.py#L155
looks like the number of knn is hardcoded here, which of course is bad since it's a parameter we set earlier.

A quick fix would be to replace the hardcoded 16 with the actual number of neighbours taken from `neighbor_xyz.shape` directly. I don't remember the shape of  `neighbor_xyz`, but something like this should work, according to the error message
```
repeated_xyz = xyz.repeat(1, 1, 1, neighbor_xyz.shape[3])
```
Let me know if this work for you please. It's possible it may break something else. We did a bit of refactoring to parameterize the model before publishing it, but it's possible that we've missed a few points here and there.

**Comment by kimdn** [comment]
@Gabry993 

Awesome, 
`repeated_xyz = xyz.repeat(1, 1, 1, neighbor_xyz.shape[3])`
works as

`[kimd999@tlogin3 randla-net-pytorch_idsia_pnnl]$ tail -f RandLA_train_13_14_16_validate_15_v_acc_patience_93754.err
Train:  12%|█▏        | 58/500 [01:52<13:56,  1.89s/it, t_loss=2.94663, t_acc=0.42390]...`


Thank you.
